### ISSUE TITLE
Set up project

### ISSUE THREAD

**Issue by marcoow** [blogic/ucentral-pwa#1]
First steps first – we need a new Ember app. We won't be using `ember-data` so we can drop that and we should add `ember-test-selectors` so `data-test-` selectors will be removed in production properly.

### TODO

* [x] `ember new`
* [x] remove `ember-welcome-page`
* [x] remove `ember-data`
* [x] add `ember-test-selectors`
* [x] add `ember-intl`
* ~add `ember-intl` polyfills~
* [x] [set the locale statically (for now) in the `application` route's `beforeModel` method](https://ember-intl.github.io/ember-intl/docs/quickstart#4-configure-ember-intl)
* [x] [enable the `no-bare-strings` template linting rule](https://ember-intl.github.io/ember-intl/docs/quickstart#4-configure-ember-intl)
* [x] enable `errorOnNamedArgumentMismatch`, `errorOnMissingTranslations`, `stripEmptyTranslations` [ember-intl configuration settings](https://ember-intl.github.io/ember-intl/docs/guide/addon-configs)
* [x] add `ember-intl-analyzer`

### Open Questions

* [x] we need to define what browsers we want to support to decide on the polyfills we need to install for those; of course service workers are only supported in modern browsers anyway but if we wanted to allow older browsers to use this still which would be possible we'd have to install [polyfills for some `Intl` APIs](https://ember-intl.github.io/ember-intl/docs/runtime-requirements) **Update: we won't support IE11 or Opera which means no polyfills are necessary**

**Comment by BobrImperator** [comment]
- add ember-intl
- setup tailwindcss

**Comment by marcoow** [comment]
@BobrImperator I'd do the tailwind setup in a task in which we actually build components

**Comment by marcoow** [comment]
done
