### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by marcoow** [blogic/ucentral-pwa#2]
We'll be using GitHub Actions for CI. We should use Volta for stable dependencies and run linting and testing in parallel.

### TODO

* [x] setup Volta by adding something like this to `package.json` (using whatever the latest stable versions of node and yarn are):

  ```json
  "volta": { "node": "12.13.1", "yarn": "1.22.10" }
  ```

* [x] add `.github/workflows/ci.yml` configuration based on https://github.com/blogic/ucentral-pwa/new/main?filename=.github%2Fworkflows%2Fnode.js.yml&workflow_template=node.js but using [`volta-cli`](https://github.com/volta-cli/action)
* [x] configure to run linting and testing in parallel for maximum performance

**Comment by marcoow** [comment]
this will only be closed by #8 actually
