### ISSUE TITLE
QR code component

### ISSUE THREAD

**Issue by marcoow** [blogic/ucentral-pwa#27]
The app is supposed to offer sharing network settings/credentials via a QR code:

<img width="314" alt="Bildschirmfoto 2021-05-25 um 11 27 15" src="https://user-images.githubusercontent.com/1510/119474188-2f14f980-bd4c-11eb-8945-24a57dd90033.png">

The QR code is a special code that will make the mobile OS install/configure the network automatically. The code encodes a simple string ([spec](https://github.com/zxing/zxing/wiki/Barcode-Contents#wi-fi-network-config-android-ios-11)). That string can be converted to a QR code with a library like [qrcode](https://www.npmjs.com/package/qrcode).

The sharing button is supposed to open a sharing dialog using the [web share API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share).

### TODO

- [x] add `QrCode` component that receives `@ssid`, `@encryption`, `@password`, `@isHidden` arguments and renders a QR code based on those
- [x] share the QR code via the web share API

### Open Questions

- [x] how exactly can we share the network settings (as an image or data url?)
