### ISSUE TITLE
Qr code screen

### ISSUE THREAD

**Issue by marcoow** [blogic/ucentral-pwa#28]
The QR code screen is accessible from the start page and simply shows the QR code for the currently configured network:

![screen](https://user-images.githubusercontent.com/1510/119470696-dee86800-bd48-11eb-8d27-d6e599f1f7e8.png)

### TODO

- [x] add `/qr-code` (or so) route
- [x] on the route, load the current network configuration
- [x] for the network configuration, render the `QrCode` component (see #27)
- [x] add back navigation to layout

### Open Questions

- [ ] what is the correct endpoint to load the network configuration from?

**Comment by pichfl** [comment]
### Arrow Left Icon

```svg
<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12.707 4.293a1 1 0 010 1.414L7.414 11H19a1 1 0 010 2H7.414l5.293 5.293a1 1 0 01-1.414 1.414l-7-7-.073-.082a1.005 1.005 0 01-.007-.008l.08.09A1.008 1.008 0 014 12.02v-.037c0-.024.002-.048.004-.071L4 12a1.008 1.008 0 01.213-.617c.025-.031.051-.062.08-.09l7-7a1 1 0 011.414 0z" fill="currentColor" fill-rule="nonzero"/></svg>
```

Set color by replacing `currentColor` with a hex value or if the SVG is inlined in the DOM by setting the css color for the parent element (currentColor will inherit the color from the parent)

**Comment by marcoow** [comment]
closed via #36
