### ISSUE TITLE
QR code screen after setup wizard

### ISSUE THREAD

**Issue by marcoow** [blogic/ucentral-pwa#29]
Once the setup flow has been completed, we'll show a QR code with the configuration of the network that was just set up with the wizard:

![success](https://user-images.githubusercontent.com/1510/119471996-1dcaed80-bd4a-11eb-9088-0547093a2f24.png)

The QR code component will be built in #27. The screen overall is pretty similar to the one being built in #28. However, we might not have to make an additional request for loading the configuration here (since we might get that in the response to the last step of the setup wizard) and show different text.

### TODO

- [x] add a new `/setup/success` (or so) route
- [x] move configuration into `currentDevice` service so that settings are available there
- [x] render the `Qr code` component

Although there will likely be a bit of duplication between this and #28, I'd rather duplicate the code for now instead of looking for ways to share code between the routes which might complicate things quite a bit.

### Open questions

- [ ] does the response we receive when applying the changes in the last step of the wizard in fact contain the values we need or would we have to make an additional request?

Related to #38
