### ISSUE TITLE
Password visiblity toggle

### ISSUE THREAD

**Issue by BobrImperator** [blogic/ucentral-pwa#30]
![image](https://user-images.githubusercontent.com/15948633/119547923-fa2d9480-bd95-11eb-9ac4-9616dce2b267.png)

![image](https://user-images.githubusercontent.com/15948633/119547220-21379680-bd95-11eb-9abe-eae40246b344.png)

Password visibility button required in #4 couldn't be implemented because of missing assets - svg icons.

We will build the toggle ourselves as there aren't any good libs that could provide that instead.

### TODOS
- [ ] add password visiblity toggle to PasswordInput
- [ ] PasswordInput needs to accept additional options `showVisiblityToggle`  that will determine whether the icon is visible.
- [ ] create wrapper element for input field and icon

**Comment by pichfl** [comment]
### SVG Code for Icons

```svg
<!-- eye -->
<svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="M15.95 7.733C15.816 7.467 13.01 2 8 2S.184 7.467.05 7.733c-.067.2-.067.4 0 .6C.184 8.533 2.99 14 8 14s7.816-5.467 7.95-5.733a.735.735 0 000-.534zM8 12.667c-3.608 0-5.946-3.6-6.614-4.667C1.987 6.933 4.392 3.333 8 3.333s5.946 3.6 6.614 4.667c-.668 1.067-3.006 4.667-6.614 4.667zm0-7.334c-1.47 0-2.672 1.2-2.672 2.667A2.677 2.677 0 008 10.667c1.47 0 2.672-1.2 2.672-2.667A2.677 2.677 0 008 5.333zm0 4c-.735 0-1.336-.6-1.336-1.333S7.265 6.667 8 6.667c.735 0 1.336.6 1.336 1.333S8.735 9.333 8 9.333z" fill="currentColor" fill-rule="nonzero"/></svg>
```

```svg
<!-- eye / slashed -->
<svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="M5.933 3c-.066-.4.134-.733.534-.8.466-.133 1-.2 1.533-.2 5 0 7.8 5.467 7.933 5.733.067.2.067.4 0 .6-.4.8-.933 1.534-1.533 2.267-.133.133-.333.267-.533.267-.134 0-.334-.067-.4-.134-.267-.266-.334-.666-.067-.933a9.58 9.58 0 001.2-1.667c-.6-1.066-3-4.666-6.6-4.666-.4 0-.867.066-1.267.133-.333-.067-.666-.267-.8-.6zM15.8 15.8a.605.605 0 01-.467.2.605.605 0 01-.466-.2l-3-3C10.733 13.6 9.4 14 8 14 3 14 .2 8.533.067 8.267a.925.925 0 010-.6C.8 6.267 1.867 5 3.067 4L.2 1.133A.644.644 0 01.2.2a.644.644 0 01.933 0L15.8 14.867a.644.644 0 010 .933zM6.6 8.067c0 .333.133.666.4.933.4.333.867.4 1.333.267L6.667 7.6c0 .2-.067.333-.067.467zm4.333 3.8l-1.6-1.534c-.4.267-.933.4-1.4.4a2.576 2.576 0 01-1.8-.733c-.533-.467-.8-1.133-.866-1.867 0-.533.133-1.066.4-1.533L4 4.933C3 5.8 2.133 6.8 1.4 8c.6 1.067 3 4.667 6.6 4.667 1 0 2-.267 2.933-.8z" fill="currentColor" fill-rule="nonzero"/></svg>
```
