### ISSUE TITLE
NetworkMap

### ISSUE THREAD

**Issue by BobrImperator** [blogic/ucentral-pwa#39]
Network map is a summary of access points and connected devices within the network.

Overview
![image](https://user-images.githubusercontent.com/15948633/120329579-49bb1580-c2ec-11eb-8ee9-856d64a4b28b.png)
https://share.goabstract.com/30871437-23aa-453d-bb0c-96b8a1be9a4d?mode=design&sha=c609991f3db28c212d5b7a820c3a81423b3681a6
Overview is a summary of APs and connected devices within the network.
It shows how many APs and devices tere are in total as well as a list of access points which when are clicked they redirect to their 'detail' route.
Each of the devices have a status indicator saying whether a device is offline or online.

Detail
![image](https://user-images.githubusercontent.com/15948633/120329650-59d2f500-c2ec-11eb-8234-f0fd6fcfb696.png)
https://share.goabstract.com/546fb614-65a0-410c-8490-cc3f3d20d608?mode=design&sha=c609991f3db28c212d5b7a820c3a81423b3681a6

### Questions
- [ ] What exactly the device colour status mean?
  - [ ] What green stands for?
  - [ ] What orange stands for?
  - [ ] What red stands for?
  Does this relate to they 'health' in percents?
  Would offline or 0 - 10, 10 - 70, 80 - 100 ranges for red, orange, green respectively make sense?
  https://github.com/Telecominfraproject/wlan-cloud-ucentralgw/blob/master/openapi/ucentral/ucentral.yaml#L1727
- [ ] Where do we get the data from?
  - [ ] Devices list https://github.com/Telecominfraproject/wlan-cloud-ucentralgw/blob/master/openapi/ucentral/ucentral.yaml#L1727
  https://github.com/Telecominfraproject/wlan-cloud-ucentralgw/blob/master/openapi/ucentral/ucentral.yaml#L76
  - [ ] Access points or other devices making the mesh seem to be easily identifiable by their `deviceType=AP | SWITCH | MESH | IOT`, How to identify devices connected to a particular access point, switch...?
- [ ] Given there are multiple device types, are we going to show other devices than switch? If so, should we have different icons for them?

### Resources
- CLI, can also be used to inspect requests
There's package with sample requests and cli commands available to download from slack
https://ucentral-ui.slack.com/archives/C020QQ6KQ06/p1622010151002800
- OpenAPI
https://github.com/Telecominfraproject/wlan-cloud-ucentralgw/blob/master/openapi/ucentral/ucentral.yaml#L1777

### TODOS
- [x] Create network_map and network_map/:id routes
- [x] Allow for redirecting from 'index' to network_map.
- [x] Mock 'list devices' request with multiple 'deviceTypes'
- [x] Show devices count with `deviceType=AP`
- [x] Show all devices count
- [x] On AP list show their SSIDs, health status and amount of connected devices.
- [x] Create device tiles using Uc::LinkTile which once are clicked they redirect to `network_map/:deviceId` route.
- [x] Allow for Uc::LinkTile to show device health status.
Perhaps creating another component that's similar to Uc::LinkTile might be a better solution so not to create a too big component
- [x] On `network_map/:deviceId` route - Access point details route, show a list of devices that are connected to it.
  - remaining question is, how do we know that a device is connected to this particular access point?
- [x] On the devices list show their names, mac addresses and Ip addresses.
- [x] Since for this task we're data heavy, it'd be best to define ember-cli-mirage factories for testing and development.
