### ISSUE TITLE
Auth flow

### ISSUE THREAD

**Issue by marcoow** [blogic/ucentral-pwa#4]
In order to manage network, first step is to log-in to Ucentral app where users will be able to manage their devices.
![Authenticate_IPAddress](https://user-images.githubusercontent.com/15948633/118632877-29aa3300-b7d1-11eb-9b07-15e04f53808e.png)
https://share.goabstract.com/c7f8eb13-f97c-43f7-9a9c-9cc7a2a0f3fe
![Authenticate_Password](https://user-images.githubusercontent.com/15948633/118632861-257e1580-b7d1-11eb-861c-edc0676729f7.png)
https://share.goabstract.com/0f36291b-4463-49c0-a18d-96dc8ec66d5a
![Authenticate_ErrorHandling_FieldError](https://user-images.githubusercontent.com/15948633/118632886-2c0c8d00-b7d1-11eb-84f4-b0590ed75001.png)
https://share.goabstract.com/801b353c-8e8f-48e9-a096-cb9c6924d6ba

Auth process is a multi-step form where users need to provide device ip address and password.
It has only a logo, header and section description text as well as inputs with labels and eventual error messages and a button to either proceed to next step or login once the multi-step process is finished.

✅  Given all data was correct and login process succeeded, two behaviours may occur.
- 🥇 Given user is setting up network for the first time, then
Then they're redirected to a "NewSetup" wizard #6 

- 👍 Given user has already existing network
Then they're redirected to a "dashboard" #5 

🛑 Given some data was incorrect
Then an input highlights and shows an error message under it.

### Notes
'Forgot password' and 'Where is my IP Address' features have been removed, and won't be implemented.

### Questions
- [ ] Does logo in header link to anywhere?
- [ ] How should the button look like in disabled state?
![Screenshot 2021-05-19 at 20 42 28](https://user-images.githubusercontent.com/15948633/118866870-bdb7ef80-b8e2-11eb-8b4c-de1415635e21.png)
- [ ] How should the button look when in pending state (e.g. while the request is being processed)?
- [ ] How do we go back to IP address screen in case both credentials are wrong, not just password?

### TODOS
- [x] setup css libriaries
tailwind - requires to be initialised with a configuration file, it can be generated with `tailwind init app/tailwind/config.js --full` command. We're passing 'full' flag because we want the whole default configuration provided.
Tailwind setup guide: https://dev.to/jamesbyrne/using-tailwindcss-with-ember-41el
- [x] Configure tailwind theme to match the designs.
- [x] ember-css-modules
We will be using ember-css-modules addon together with tailwind classes used in css rather than html.
We'll be using all linting rules provided by:
https://github.com/simplabs/ember-template-lint-plugin-css-modules
- [x] create 'auth' route
  - [x] Auth component
     If the field is empty, then we should put it in error state.
   When authentication request is rejected it should put inputs in error state and show a failure message.
- [x] Layout
  - [x] page Header component
   Should include a logo, configurable title and description.
  - [x] Button component
    - [x] Pending state
    - [x] Disabled state
    ember-concurrency(?)
  - [x] Input component
    - [x] label
    - [x] error state
    - [x] error message
  - [ ] PasswordInput component
    -  [ ] Visibility feature - need icon asset
- [x] auth service (async login() just always returns true for now)
login method returns a promise that returns a boolean when authentication succeeds or fails, but will return an error in case e.g. connection issue.

### Dependencies
depends on #1 

ember-concurrency
ember-concurrency-decorators
We'll be using all linting rules provided by:
https://github.com/simplabs/eslint-plugin-ember-concurrency

**Comment by BobrImperator** [comment]
In order to manage network, first step is to log-in to Ucentral app where users will be able to manage their devices.
![Authenticate_IPAddress](https://user-images.githubusercontent.com/15948633/118632877-29aa3300-b7d1-11eb-9b07-15e04f53808e.png)
![Authenticate_Password](https://user-images.githubusercontent.com/15948633/118632861-257e1580-b7d1-11eb-861c-edc0676729f7.png)
![Authenticate_ErrorHandling_FieldError](https://user-images.githubusercontent.com/15948633/118632886-2c0c8d00-b7d1-11eb-84f4-b0590ed75001.png)

Auth process is a multi-step form where users need to provide device ip address and password.
It has only a logo, header and section description text as well as inputs with labels and eventual error messageds and a button to either proceed to next step or login once the multi-step process is finished.

✅  Given all data was correct and login process succeeded, two behaviours may occur.
- 🥇 Given user is setting up network for the first time, then
Then they're redirected to a "NewSetup" wizard 

- 👍 Given user has already existing network
Then they're redirected to a "dashboard" #5 


auth route
dashboard route
Header component
Auth (or whatever) component
Button component
Input component
PasswordInput component
auth service (async login() just always returns true for now)
-----
depends on #1 
tailwind (ember-css-modules in case we need our own styles)
ember-intl

**Comment by marcoow** [comment]
> How do we go back to IP address screen in case both credentials are wrong, not just password?

I think in the case of any error other than a 403 (or whatever mechanism the router API uses to indicate wrong credentials) we could go back to the IP entry?

**Comment by marcoow** [comment]
@Paarmita can you have a look at the open questions above and update the design if necessary?

**Comment by marcoow** [comment]
@BobrImperator I just realized I think we **do** want to use ember-simple-auth. After all we'll also want to have features like enforcing authentication for particular routes (e.g. the dashboard – #5) etc. which we'd simply have to re-implement when **not** using ember-simple-auth.

**Comment by BobrImperator** [comment]
@marcoow Yeah that's probably a good idea, then we'd only need to take care of an authenticator.
