### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by marcoow** [blogic/ucentral-pwa#43]
The app is supposed to be usable as a PWA. It should be installable to the home screen and work offline (e.g. when the device is connected to the access point but that doesn't have a connection to the internet or the access point reboots and the WiFi goes away intermittently, etc.).

### TODO

- [x] add `manifest.json` to control start URL, app name, colors, icon etc.
- [x] add [`ember-cli-workbox`](https://github.com/BBVAEngineering/ember-cli-workbox)
  - [x] pre-cache all static assets
  - [x] serve `index.html` when device is offline (see https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offline_page_only)
- [x] set up testing via Lighthouse CI *(we're not really interested in the performance metrics but the PWA checks only but getting the performance metrics for free as part of this is nice)*

### Resources

* the easiest way to create the manifest is to use a generator like https://app-manifest.firebaseapp.com
