### ISSUE TITLE
Network settings

### ISSUE THREAD

**Issue by BobrImperator** [blogic/ucentral-pwa#46]
Network settings is a route that contains links to changing network credentials, its name and password.

https://share.goabstract.com/5f76544c-bebf-4fd2-8ad3-7f7027c38064?mode=design&sha=c609991f3db28c212d5b7a820c3a81423b3681a6
Network Settings
![image](https://user-images.githubusercontent.com/15948633/121077522-01ae5e00-c7d8-11eb-8a91-862bd496ef93.png)

Network Settings / network name
https://share.goabstract.com/e91e2e29-cc6c-4ed5-95c2-d79ef6efa32d?mode=design&sha=c609991f3db28c212d5b7a820c3a81423b3681a6

Network Settings /  network password
https://share.goabstract.com/834521ae-1219-4f1f-8312-90f9b7994ddd?mode=design&sha=c609991f3db28c212d5b7a820c3a81423b3681a6

### Questions
- [ ] Are these the correct endpoints that interest us?
https://github.com/Telecominfraproject/wlan-cloud-ucentralgw/blob/master/openapi/ucentral/ucentral.yaml#L437
https://github.com/Telecominfraproject/wlan-cloud-ucentralgw/blob/master/openapi/ucentral/ucentral.yaml#L1777
- [ ] To change wifi name for example, is payload `{ configuration: '{ ssid: 'new_name' }' }` correct?
- [ ] Should frontend validate if new password is matching?
- [ ] Does the payload to create a new password is ``{ configuration: '{ current_password: 'old_password', password: 'new_password' }' }``

### TODOS
- [x] Create 'network_settings' route.
- [x] Create 'network_settings/network_name' route.
- [x] Create 'network_settings/network_password' route.
- [x] Add a link from 'dashboard' to 'network_settings'
- [x] Add links from 'network_settings' to child 'network_name' 'network_password' routes using `Uc::LinkTile`.
- [x] Back navigation icon can be reused from QR code view
