### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by marcoow** [blogic/ucentral-pwa#5]
After user is logged in they can easily see available options on a dashboard screen.

![Dashboard_v3](https://user-images.githubusercontent.com/15948633/118658261-82d39000-b7ec-11eb-99b6-52b518b57442.png)
https://share.goabstract.com/8ee35412-03d6-40e1-9734-b145798e57bc

Dashboard is a simple view with logo, header being the name of a device that we logged in to, description and a list of available options.
Each option is a tile with a description and an icon inside.

### Questions
- [x] How should we manage icons?
font-face, svgs or pngs?

### TODOS
- [x] create 'dashboard' route
- [x] create Tile component
- [ ] create ButtonWithIcon component
- [x] use layout from auth screen

depends on #4

**Comment by marcoow** [comment]
> How should we manage icons? `font-face`, SVGs or PNGs?

I'd use SVGs with some inlining mechanism

**Comment by marcoow** [comment]
I created this as the `index` route since that's really what we want it to be
